DROP DATABASE IF EXISTS game;

CREATE DATABASE IF NOT EXISTS game;

CREATE TABLE IF NOT EXISTS game.games (
	game_id INT PRIMARY KEY AUTO_INCREMENT,
    play_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winner VARCHAR(100)
) ENGINE=InnoDB AUTO_INCREMENT=1001;

CREATE TABLE IF NOT EXISTS game.logs (
	log_id INT PRIMARY KEY AUTO_INCREMENT,
    play_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    games_winer_id VARCHAR(100) NOT NULL, 
    name VARCHAR(100) NOT NULL, 
    card1 CHAR(8) NOT NULL, 
    card2 CHAR(8) NOT NULL, 
    card3 CHAR(8) NOT NULL, 
    point TINYINT NOT NULL, 
    biggest_card CHAR(2) NOT NULL,
    game_id INT,
    FOREIGN KEY  game (game_id) REFERENCES games(game_id)
) ENGINE=InnoDB AUTO_INCREMENT=10001;

